### ISSUE TITLE
Register custom provider

### ISSUE THREAD

**Issue by jojomartius** [ADmad/cakephp-social-auth#104]
In order to use the OAuth / OpenID Connect together with custom or not-listed providers it would be nice to be able to load provider configurations from outside. 
As far as I can see the SocialConnect\Auth\CollectionFactory supports a register method to side-load custom implementations.
Can somebody provide some information or share ideas how to load a custom provider from inside Cake's Application.php?

**Comment by ADmad** [comment]
We could add a new config to allowing setting a `CollectionFactory` which would be passed to the `Service`'s constructor here https://github.com/ADmad/cakephp-social-auth/blob/ada00abf54fb9ff941a8673feca83d0b66c956c4/src/Middleware/SocialAuthMiddleware.php#L536.

PR welcome.

**Comment by jojomartius** [comment]
Puh.. do you think setting up a new/custom CollectionFactory is best? Wouldn't it be easier to add a new provider via

`(new CollectionFactory)->register(.., ...);`

?

**Comment by jojomartius** [comment]
Updated/extended Readme and added code change
