### ISSUE TITLE
error in getUser function

### ISSUE THREAD

**Issue by makkus183** [ADmad/cakephp-social-auth#14]
I get the following Argument error when i use your `getUser()` function as described in [README.md](https://github.com/ADmad/cakephp-social-auth/blob/master/README.md)  in `src/Model/Table/UsersTable.php`
```
Argument 1 passed to App\Model\Table\UsersTable::getUser() must be an instance of App\Model\Table\EntityInterface, instance of ADmad\SocialAuth\Model\Entity\SocialProfile given [APP/Model/Table/UsersTable.php, line 83]```

**Comment by JeremyWinalist** [comment]
Hi @ADmad why did you close this ? I'm having same error.

**Comment by ADmad** [comment]
The README has already been updated https://github.com/ADmad/cakephp-social-auth/commit/ac2a86c6b01b4be43b22c9b8f131392c2c957bcc.

**Comment by JeremyWinalist** [comment]
@ADmad sorry I read wrong. I had issue when trying to use `$session`, second parameter of `getUser`function.

**Comment by rfeugenio** [comment]
Same error with me.

Too few arguments to function App\Model\Table\UsersTable::getUser(), 1 passed and exactly 2 expected

**Comment by ADmad** [comment]
The feature for recieving session as argument hasn't been released yet. You need to use the `master` branch for now.
