### ISSUE TITLE
how to do with twitter ?

### ISSUE THREAD

**Issue by maungyehtunzaw** [ADmad/cakephp-social-auth#18]
I am ok for facebook login but i was configure like facebook to twitter but..i got errors..

> **Provider response is not success SocialConnect\Provider\Exception\InvalidResponse errors**

how to configure for twitter login..
Please ..

**Comment by ADmad** [comment]
Read the hybridauth docs on how to configure Twitter provider.

**Comment by anuj9196** [comment]
I tried to do as given in hybridauth
```
'Twitter' => [
       'enabled' => true,
       'keys' => [
               'key' => '*******',
               'secret' => 'd3DxnqDvh*******************zp1oY******'
        ],
        'includeEmail' => true // Only if your app is whitelisted by Twitter Support
],
```

But it is giving error as
```
 Provider response is not success 
Undefined index: applicationId [ROOT/vendor/socialconnect/auth/src/Auth/CollectionFactory.php, line 86]
Undefined index: applicationSecret [ROOT/vendor/socialconnect/auth/src/Auth/CollectionFactory.php, line 86]
```

**Comment by ADmad** [comment]
My previous comment should have said "SocialConnect/auth" docs, not "hybridauth" docs.

**Comment by anuj9196** [comment]
Hey @maungyehtunzaw , Have you solved issue with twitter login?

I tried as given in example https://github.com/SocialConnect/auth/blob/dcdeb91b0c62a8cb574c7d02b45957f69d55fa9d/example/config.php.dist#L16

But still same error is there.

**Comment by thapachaki** [comment]
I have uncheked "Enable Callback Locking" and it works!
![captura de pantalla 2018-04-27 a la s 16 33 40](https://user-images.githubusercontent.com/12816865/39383897-f372c314-4a38-11e8-98d3-b19594cf8ec7.png)
