### ISSUE TITLE
Error Auth provider_failure

### ISSUE THREAD

**Issue by datnguyenthang** [ADmad/cakephp-social-auth#19]
I get error when auth, then redirect to
login?error=provider_failure#_=_
both googe and facebook
i debug and see this line error:
211: $identity = $provider->getIdentity($accessToken); 
How to fix it?

**Comment by ADmad** [comment]
If authenticating through provider fails there's  nothing the plug in can do. Make sure  you  have configured  the provider  properly.

**Comment by datnguyenthang** [comment]
i try to many way to setup, but it only return login?error=provider_failure#=
My setup:
`$middleware
            // Catch any exceptions in the lower layers,
            // and make an error page/response
            ->add(ErrorHandlerMiddleware::class)

            // Handle plugin/theme assets like CakePHP normally does.
            ->add(AssetMiddleware::class)

            // Apply routing
            ->add(RoutingMiddleware::class)
			->add(new \ADmad\SocialAuth\Middleware\SocialAuthMiddleware([
				// Request method type use to initiate authentication.
				'requestMethod' => 'POST',
				// Login page URL. In case of auth failure user is redirected to login
				// page with "error" query string var.
				'loginUrl' => '/accounts/login',
				// URL string or array to redirect to after authentication.
				'loginRedirect' => '/',
				// Boolean indicating whether user identity should be returned as entity.
				'userEntity' => false,
				// User model.
				'userModel' => 'Accounts',
				// Finder type.
				'finder' => 'all',
				// Fields.
				'fields' => [
					'password' => 'password',
				],
				// Session key to which to write identity record to.
				'sessionKey' => 'Auth.User',
				// The methods in user model which should be called in case of new user.
				// It should return a User entity.
				'getUserCallback' => 'getUser',
				// SocialConnect Auth service's providers config. https://github.com/SocialConnect/auth/blob/master/README.md
				'serviceConfig' => [
					'provider' => [
						'facebook' => [
							'applicationId' => 'Mynumber',
							'applicationSecret' => 'Mynumber',
							'scope' => [
								'email',
							],
							'fields' => [
								'email',
								// To get a full list of all posible values, refer to
								// https://developers.facebook.com/docs/graph-api/reference/user 
							],
						],
						'google' => [
							'applicationId' => 'Mynumber-upocqh94prcn8jojcek0pb9qlhqbacb5.apps.googleusercontent.com',
							'applicationSecret' => 'Mynumber',
							'scope' => [
								'email',
							],
							'fields' => [
								'email',
								// To get a full list of all posible values, refer to
								// https://developers.facebook.com/docs/graph-api/reference/user 
							],
						],
					],
				],
			]));`
Could you give example config in Application.php
