### ISSUE TITLE
how to set up authorized redirect URIs 

### ISSUE THREAD

**Issue by maungyehtunzaw** [ADmad/cakephp-social-auth#21]
I have poemhive.com/member/login
-------
i add authorized redirect URLs

http://www.poemhive.com

in google authorized redirect URIs 

but i got errors

400. That’s an error.

**Error: redirect_uri_mismatch

The redirect URI in the request, http://www.poemhive.com/social-auth/callback/google/, does not match the ones authorized for the OAuth client. Visit https://console.developers.google.com/apis/credentials/oauthclient/840564626539-4gvde8022tb25epblfd7ufdbvqgjv51e.apps.googleusercontent.com?project=840564626539 to update the authorized redirect URIs.**

**Comment by ADmad** [comment]
You need to set the redirect uri to exactly the one shown in error.

**Comment by maungyehtunzaw** [comment]
![ssssssssssss](https://user-images.githubusercontent.com/5591177/32873283-8fbdbcf6-cab9-11e7-9a13-7dd0ee75b49f.JPG)

I added exactly shown in errors..
