### ISSUE TITLE
How to see the output of provider_failure?

### ISSUE THREAD

**Issue by ntoka** [ADmad/cakephp-social-auth#23]
Hi, we are having problems implementing google+ login in our Cakephp project. We've done everything according the example given in the docs, we configured the credentials and oAuth consent for google+ api and yet we're getting only provider_failure.

Where/how can we see what exactly failed?

**Comment by ADmad** [comment]
Currently no :(  It will require implementing logging the details of exception thrown by socialauth/connect lib. In the meantime you can just debug the exception instance that is caught around line 212 or `SocialAuthMiddleware`.
