### ISSUE TITLE
Provider_failure because of failure to verify SSL

### ISSUE THREAD

**Issue by ntoka** [ADmad/cakephp-social-auth#24]
Hi, we debugged the provider_failure errors and it seems that we cannot get the SSL verified with an error:

`exception 'Cake\Core\Exception\Exception' with message 'fopen(): SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed fopen(): Failed to enable crypto fopen(https://accounts.google.com/o/oauth2/token): failed to open stream: operation failed'`

Any idea how to fix this? This happens only using Google login - Facebook works fine. 

Thanks in advance

**Comment by ADmad** [comment]
For debugging purposes try replacing `vendor/cakephp/cakephp/config/cacert.pem` with latest file from https://github.com/paragonie/certainty/tree/master/data  (with same name of course).

**Comment by ntoka** [comment]
Unfortunately that didn't help

**Comment by ADmad** [comment]
What's your openssl version? You can use `openssl version` on command line to know.

**Comment by ntoka** [comment]
1.0.1f

**Comment by ADmad** [comment]
Thought so, I too had this problem on ubuntu 14.04 with openssl 1.0.1f. Upgrading the `openssl` package fixed the issue. You need to do the same.
