### ISSUE TITLE
Best way to limit the number of registrations?

### ISSUE THREAD

**Issue by HelloLudger** [ADmad/cakephp-social-auth#28]
Hi,

if I want to allow only a limited number of registrations, what would be the best way?

If I check within the "getUser", the profile already exists and it should return an entity, but I would prefer redirecting to a page...

Is there something like "beforeRegister"?

**Comment by ADmad** [comment]
You can throw an exception from `getUser()`. Use [responseHeaders()](https://api.cakephp.org/3.5/class-Cake.Core.Exception.Exception.html#_responseHeader) to set redirection headers before throwing the exception.
