### ISSUE TITLE
Why you didn't build this plugin with HybridAuth?

### ISSUE THREAD

**Issue by BassemN** [ADmad/cakephp-social-auth#29]
Hello,

Out of curiosity, Why you didn't build this plugin with HybridAuth?

Thanks

**Comment by ADmad** [comment]
In spite of it's popularity HybridAuth's development is pretty flaky. Things break too often for my liking and I end up getting tickets on my plugin. Recent example ADmad/CakePHP-HybridAuth#113.

It's seems to lack a primary maintainer who can devote enough time. The 2.x code is pretty outdated and the 3.x has been in development for too long (although checking it now it seems activity has picked up again).

**Comment by BassemN** [comment]
Thanks for your time

**Comment by ADmad** [comment]
An update: Hybridauth v3 still doesn't hasn't been released, stuck on rc3 for months.

There's also a minor concern like the following ticket. v3 is still slated to PHP 5.4, a version for which support has been discontinued over 3 years ago.

`https://github.com/hybridauth/hybridauth/issues/904`

**Comment by BassemN** [comment]
Thanks for this update :+1:
