### ISSUE TITLE
Missing Route error

### ISSUE THREAD

**Issue by hanuman1989** [ADmad/cakephp-social-auth#31]
I get the following error when using cakephp-social-auth plugin:
<?php echo $this->Form->postLink(
			'Login with Facebook',
			[
				'plugin' => 'ADmad/SocialAuth',
				'controller' => 'Users',
				'action' => 'login',
				'provider' => 'facebook',
			   '?' => ['redirect' => $this->request->getQuery('redirect')]
			]
		);
?>

![route_error](https://user-images.githubusercontent.com/3963974/34239312-a68d8428-e62c-11e7-96c4-c0bcb73a7bcf.png)

**Comment by ADmad** [comment]
Make sure you have followed readme properly and the routes file of plugin is loaded.

**Comment by ADmad** [comment]
You are supposed to use `'controller' => 'Auth'` not `'controller' => 'Users'`, as stated in readme.

**Comment by BassemN** [comment]
I'm getting the following error

`
Error: A route matching "array ( 'plugin' => 'ADmad/SocialAuth', 'controller' => 'Auth', 'action' => 'login', 'provider' => 'facebook', '?' => array ( 'redirect' => NULL, ), 'prefix' => 'auth', '_ext' => NULL, )" could not be found.
`

and by checking the plugin files, I didn't see a controller called `Auth` as you can see in this image 
![image](https://user-images.githubusercontent.com/3768012/38388547-d34085f0-391b-11e8-8374-2a79f0597dfc.png)

**Comment by ADmad** [comment]
The plugin doesn't have an actual AuthController. The requests are handled by the SocialAuthMiddleware itself.

**Comment by BassemN** [comment]
so what do you think the reason of that error?

**Comment by BassemN** [comment]
I got the reason of that error, I was adding the links to providers into a page with a prefix so the form generated link was with that prefix so I added `'prefix' => false,` the error disappeared so I think you need to update the readme with the following code

```php
    <?php
    echo $this->Form->postLink(
        'Login with Facebook',
        [
            'prefix' => false,
            'plugin' => 'ADmad/SocialAuth',
            'controller' => 'Auth',
            'action' => 'login',
            'provider' => 'facebook',
            '?' => ['redirect' => $this->request->getQuery('redirect')]
        ]
    );
    ?>
```

**Comment by ADmad** [comment]
`'prefix' => 'auth'` that's your problem. Set prefix to false when generating URL.

**Comment by ADmad** [comment]
Guess I'll have to update the readme for those who don't pay attention to error messages.

**Comment by BassemN** [comment]
Thanks allot @ADmad
