### ISSUE TITLE
Facebook: error in link

### ISSUE THREAD

**Issue by pieroGit** [ADmad/cakephp-social-auth#32]
i have an error when i click in post link:

document.post_5a60b534b9589662418400 is undefined

the error doesn't show when i use instagram provider

**Comment by ADmad** [comment]
`FormHelper::postLink()` generate a form tag which is submitted through javascript. It seems you have some error your app's javascript or html which cause the js to error out. You need to find the problem and fix it. It's not a problem with the plugin.

**Comment by andrekat** [comment]
Got the same problem: this happens if you create the link whithin the <form></form>element.

**Comment by ADmad** [comment]
> this happens if you create the link whithin the <form></form>element.

That's cause `postLink()` creates a `<form>` tag too and you can't have nested forms in HTML.
