### ISSUE TITLE
Internal Server Error after facebook login

### ISSUE THREAD

**Issue by farazbaloch** [ADmad/cakephp-social-auth#34]
getting this error "An Internal Server Error Occurred" after  facebook login.

call back url is

example.com/social-auth/callback/facebook/?code=AQClDML3BbjhcFVWxHoThb1xxTf4wMMnAFB1U6AHukRIwLryieqy_eh_2LqZ0kJurOhXJQbG_uAqs8FhijY-RRe6fMCBpoIliDmvbVRdVQEHZW8WKezEKIpCGsrH3WKmeHbLYrogn6MQMaNA7taJmgraVFi1pou9qU0O64mgfsg9zTYo-zISSUuUp-EyyoyjQWfFttqoJhUnxWRxITtWLJlAwWV51MA8Q3knk-mpEa4jYW2v4Yc4QuLjwTuIEMop4OX45bFKA8Slpf6gv2OkJBKi_5G-jeRvJV1639EFNhFZNlb6GZVbL0aqYvLSrWlJwmCa8YWJM6cYU37XaNHc_o1J&state=346e71e678edc2227a39e0b9cf1062e8#_=_

**Comment by ADmad** [comment]
Do you have debug turned on? If not do so that you get a more detailed error message. Also check the logs for error details.

**Comment by farazbaloch** [comment]
in config/app.php 
i have
'debug' => filter_var(env('Debug', true), FILTER_VALIDATE_BOOLEAN),

**Comment by farazbaloch** [comment]
2018-03-23 08:22:59 Error: [Cake\View\Exception\MissingTemplateException] Template file "Error/error500.ctp" is missing.
Exception Attributes: array (
  'file' => 'Error/error500.ctp',
)
Request URL: /social-auth/callback/facebook/?code=AQCsskuWiWIBE7XRzXnAhIaK7J0Wyk5-H7rqKdkp3FB37t5biOtylPX3SaMdt1daWyPIHB_0VCByALJcGmt0GZKDJ76OTnT9ktg0ek6h6NuJx7Z9Gt7M9yoPCwK19zCHVyFaO0bz1ooK0PB7xrJpP0iThisBMg0-oJNRttYsg6ezWE-MJuYxruEzIX5iDL4Q0n-J-9aEHxPdB2SE1cNQWltlKurmeXjWVVNwb-nsKaTeYXxCTMEIHFCJCg6MQTyINOkA1PZpuowsXpw9SnhUnwFVRZycA3ryR6b6ZeeQYmF6jnmXtqJoEfVC5195CNDFybdfgQRgSloTVKicdqhDbcOA&state=80234d49a0a4fa863f32985c9f9ea074
Referer URL: http://example.com/users/login?error=provider_failure
Stack Trace:
#0 /example/vendor/cakephp/cakephp/src/View/View.php(761): Cake\View\View->_getViewFileName('error500')
#1 /example/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(364): Cake\View\View->render('error500', 'error')
#2 /example/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(331): Cake\Error\ExceptionRenderer->_outputMessageSafe('error500')
#3 /example/vendor/cakephp/cakephp/src/Error/ExceptionRenderer.php(200): Cake\Error\ExceptionRenderer->_outputMessage('error500')
#4 /example/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(113): Cake\Error\ExceptionRenderer->render()
#5 /example/vendor/cakephp/cakephp/src/Error/Middleware/ErrorHandlerMiddleware.php(97): Cake\Error\Middleware\ErrorHandlerMiddleware->handleException(Object(Cake\Database\Exception), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#6 /example/vendor/cakephp/cakephp/src/Http/Runner.php(65): Cake\Error\Middleware\ErrorHandlerMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#7 /example/vendor/cakephp/debug_kit/src/Middleware/DebugKitMiddleware.php(52): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#8 /example/vendor/cakephp/cakephp/src/Http/Runner.php(65): DebugKit\Middleware\DebugKitMiddleware->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response), Object(Cake\Http\Runner))
#9 /example/vendor/cakephp/cakephp/src/Http/Runner.php(51): Cake\Http\Runner->__invoke(Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#10 /example/vendor/cakephp/cakephp/src/Http/Server.php(81): Cake\Http\Runner->run(Object(Cake\Http\MiddlewareQueue), Object(Cake\Http\ServerRequest), Object(Cake\Http\Response))
#11 /example/webroot/index.php(37): Cake\Http\Server->run()
#12 {main}

**Comment by farazbaloch** [comment]
now the errors are,
Unable to save new user
unserialize(): Error at offset 250 of 255 bytes [ROOT/vendor/admad/cakephp-social-auth/src/Database/Type/SerializeType.php, line 72]

**Comment by ADmad** [comment]
If you are using MySQL change the field type for access_token to blob. Clear any existing values.

**Comment by farazbaloch** [comment]
it worked, thank you !
