### ISSUE TITLE
Error: ADmad/SocialAuth.AuthController could not be found

### ISSUE THREAD

**Issue by JQEstrada** [ADmad/cakephp-social-auth#36]
Greetings,

I am aware that a similar issue was posted before. However, the hints given were not applicable to my case, and I am not being able to understand the origin of the error. I would appreciate if you can point in the right direction on this one, thank you in advance.

The error is generated when clicking the login link, and following through to the page http://testface.ml/social-auth/login/facebook, which doesn't redirect to facebook, but gives the error "Error: ADmad/SocialAuth.AuthController could not be found" (attached image)
![error](https://user-images.githubusercontent.com/25327318/38950990-2039c4f2-433f-11e8-84d6-ab4abd12987e.jpg)

**Comment by ADmad** [comment]
`http://testface.ml/social-auth/login/facebook` is supposed to be accessed through POST (hence the use of `Form->postLink()` in readme). Accessing through GET will result in error.

**Comment by JQEstrada** [comment]
I am sorry if I didn't explain myself perfectly. The link I am following is the one resulting from the readme instructions:

<?php echo $this->Form->postLink(
    'Login with Facebook',
    [
        'prefix' => false,
        'plugin' => 'ADmad/SocialAuth',
        'controller' => 'Auth',
        'action' => 'login',
        'provider' => 'facebook',
        '?' => ['redirect' => $this->request->query('redirect')]
    ]
); ?>

The url I mentioned is the one where the process gets stuck showing the error.
