### ISSUE TITLE
`Auth.afterIdentify` event is not firing

### ISSUE THREAD

**Issue by BassemN** [ADmad/cakephp-social-auth#39]
Hello,
The core event `Auth.afterIdentify` is no longer fired after login with the `cakephp-social-auth` plugin so any stuff depending on this event will not run. On your old plugin `CakePHP-HybridAuth` this event was firing.
Thanks

**Comment by BassemN** [comment]
Issue #26 opened to add a new event called `SocialAuth.Middleware.afterLogin` but I'm opening this issue to allow the core event `Auth.afterIdentify` to fire.

**Comment by ADmad** [comment]
It's the same event with different name. Author.afterIdentify is specific to the auh component which this plugin has nothing to do with.

**Comment by BassemN** [comment]
Thanks for your clarification.

**Comment by ADmad** [comment]
@BassemN New release done. Thanks for testing.
