### ISSUE TITLE
ADmad\SocialAuth\Middleware\SocialAuthMiddleware::config() is deprecated. Use setConfig()/getConfig() instead

### ISSUE THREAD

**Issue by degee147** [ADmad/cakephp-social-auth#49]
Using Cakephp 3.6.10
Had to modify the vendor file from 

        $this->_profileModel = $this->loadModel($this->config('profileModel'));
        $this->_profileModel->belongsTo($this->config('userModel'));

        $this->_userModel = $this->loadModel($this->config('userModel'));

To

 $this->_profileModel = $this->loadModel($this->getConfig('profileModel'));
        $this->_profileModel->belongsTo($this->getConfig('userModel'));

        $this->_userModel = $this->loadModel($this->getConfig('userModel'));

**Comment by ADmad** [comment]
The use of deprecated methods has already been fixed. Upgrade to latest version of the plugin.

**Comment by ADmad** [comment]
Sorry, it seems some methods were missed.

**Comment by ADmad** [comment]
Fixed and new release `0.5.2` done.
