### ISSUE TITLE
TableSchema::columnType() is deprecated. Use TableSchema::setColumnType() or TableSchema::getColumnType() instead

### ISSUE THREAD

**Issue by degee147** [ADmad/cakephp-social-auth#50]
Using CakePHP 3.6.10
Updated $schema->columnType('access_token', 'socialauth.serialize'); to
$schema->getColumnType('access_token', 'socialauth.serialize');

**Comment by ADmad** [comment]
You don't need to open a separate issue for each deprecation. List them in the first issue you opened. A pull request to fix is also welcome.

**Comment by degee147** [comment]
I'm a noob Sir. Not sure where to start. Can even the plugin to work for me yet, still battling
