### ISSUE TITLE
cakephp-social-auth adds #_=_ to URL?

### ISSUE THREAD

**Issue by DevMerlin** [ADmad/cakephp-social-auth#51]
I'm encountering an odd issue. On -successful- login, SocialAuth
is adding "#_=_" to the URL, and I cannot figure out how to remove this 
anchor from it. 

I understand that with a failed login, it produces the error, but it should not
be there when the login works the way it's intended to. This isn't critical for
the moment, but hoping to find a solution for it soon.

CakePHP 3.6.* Latest

Edit: Editor is not displaying the whole anchor symbol

**Comment by Rout222** [comment]
This is from facebook.

**Comment by Rout222** [comment]
Redirect again to controller / action, if #_=_ is on url
