### ISSUE TITLE
Hash id with Social Profile Table : cake php 3.6

### ISSUE THREAD

**Issue by rajume** [ADmad/cakephp-social-auth#53]
Hello i am using the hash ids plugin https://github.com/dereuromark/cakephp-hashid .  

facing issue with hash id. While implementing the social AUTH Login then user_id save as 0 in social_profiles table. in getUser() function i have encoded/decoded the user id but Profile data already fetch/saved by this plugin internally and not be able to encode/decode ids there. Also created a new model Social Profile and used the hashid in the same plugin but not successful. Kindly do needful.

**Comment by ADmad** [comment]
I don't use hashids and don't have the time or motivation to look into this. You can welcome to submit a patch to support your use case.
