### ISSUE TITLE
logout ends with error

### ISSUE THREAD

**Issue by czepter** [ADmad/cakephp-social-auth#56]
Hi! 

i am using the standard logut call in cake
`
public function logout()
    {
		return $this->redirect($this->Auth->logout());
    }
`
and reciving 

> Error: [Cake\Core\Exception\Exception] Authentication adapter "ADmad/HybridAuth.HybridAuth" was not found.

Any Ideas?

**Comment by ADmad** [comment]
This issues tracker is for the SocailAuth plugin. Not HybridAuth.
