### ISSUE TITLE
Handling denied permissions

### ISSUE THREAD

**Issue by cwaldau** [ADmad/cakephp-social-auth#57]
How should I handle permission requests that were denied by the user? Currently I ask for access to public_profile and email from facebook, but its possible to deny email (public_profile seems to be set as mandatory).

Is there a way to set email as mandatory -or- how can I handle the case where access to email was denied? I don't see a way to determine if all necessary information was allowed. The example code throws an exception if email is not set but how can I determine that from the controller in order to do something with that information?

I know that I should be sending a re-request to facebook to give the user the chance to allow their email in order to have a successful account creation but again, I don't seem to see a way to know that permissions were denied by the user.

Thanks

**Comment by ADmad** [comment]
If authentication fails you are redirected back to login url with query string `?error=provider_failure`. So you can check for that and take required action.

**Comment by ADmad** [comment]
> The example code throws an exception if email is not set but how can I determine that from the controller in order to do something with that information

Use a custom exception and setup your own handler for that that exception.
