### ISSUE TITLE
redirect_uri points to http instead of https

### ISSUE THREAD

**Issue by dlednik** [ADmad/cakephp-social-auth#62]
Is there a way to force this?
I have a site and it tries to redirect to http://domain instead of https://domain

**Comment by Mambix** [comment]
@ADmad any suggestions?

**Comment by ADmad** [comment]
Why don't you initiate the login from a https page? The redirect uri will then have https.

**Comment by Mambix** [comment]
The login is on https page

**Comment by ADmad** [comment]
This the redirect uri generated should have https too. For exactly which URL you are having problem? The redirection URL after auth is completed on provider's site?

**Comment by dlednik** [comment]
Don't want to publish URL here. Can you send me an email pls. and I'll share the live site with you that is giving me problems. Tried to look through the source code of both plugins but I could not find anything weird so far.

**Comment by ADmad** [comment]
Sorry I can't provide support via email. 

If you have set the `loginUrl` as string make sure it's full URL starting with https. If it's an array and current URL has https the `loginUrl` generated would have https too.

Only other URL the plugin sets is `redirect_uri` for social auth which would also have https based on current URL: https://github.com/ADmad/cakephp-social-auth/blob/f92ac628f9bcf28daa7576d01e61e50d38ba4885/src/Middleware/SocialAuthMiddleware.php#L460-L464

You'll need to debug yourself and find out how / where URL without https is used.

**Comment by dereuromark** [comment]
This seems like a user error. I cannot reproduce with GitHub login and normal setup.

**Comment by ADmad** [comment]
One can also explicitly set `_ssl` true in the redirect url array.
