### ISSUE TITLE
Error creating account

### ISSUE THREAD

**Issue by Smallkan** [ADmad/cakephp-social-auth#64]
![image](https://user-images.githubusercontent.com/9128062/69480034-9615c300-0de2-11ea-9d4b-45c8f1d1c384.png)

So after a lot of errors in the application setup there, I managed to make it work, but in the account creation part this error is occurring. I have not changed the default.

**Comment by ADmad** [comment]
Make your your getUser() is returning a user entity. You might have validation or application rules failing due to which saving new user is not succeeding.

**Comment by Smallkan** [comment]
I see, I took a look after the line: $ user = $ this-> newEntity and the data is coming, but it's not being saved, see ..

![image](https://user-images.githubusercontent.com/9128062/69482855-38dc3a80-0dff-11ea-9b6e-c45175c553fc.png)

![image](https://user-images.githubusercontent.com/9128062/69482868-590bf980-0dff-11ea-8872-f8a8176dfc3a.png)

I implemented role_id and uuid as these are required fields for a new account.
