### ISSUE TITLE
TypeError in return value of App\Model\Table\UsersTable::getUser() 

### ISSUE THREAD

**Issue by inigoflores** [ADmad/cakephp-social-auth#65]
Following the setup instructions in the Readme, I'm getting the following error:

>Return value of App\Model\Table\UsersTable::getUser() must be an instance of Cake\Datatsource\EntityInterface, instance of App\Model\Entity\User returned

I've managed to get it working by replacing

```php
// src/Model/Table/UsersTable.php

public function getUser(\Cake\Datasource\EntityInterface $profile, \Cake\Http\Session $session): \Cake\Datatsource\EntityInterface {
```

with 

```php
// src/Model/Table/UsersTable.php

public function getUser(\Cake\Datasource\EntityInterface $profile, \Cake\Http\Session $session): \App\Model\Entity\User {
```

Not sure if this is the correct fix.

**Comment by ADmad** [comment]
Are you sure you `User` entity class extends `Cake\ORM\Entity` (which implements `EntityInterface`)?  Maybe you are missing `use Cake\ORM\Entity` at the top of `User` entity.

**Comment by inigoflores** [comment]
Thanks for your reply.

I confirm that `User` entity class extends `Cake\ORM\Entity`, which implements `EntityInterface`.

Also `use Cake\ORM\Entity` is at the top of `User` entity.

When I add `pr(class_implements($user))` in `UsersTable::getUser()`, I get the following output:

```
Array
(
    [Cake\Datasource\InvalidPropertyInterface] => Cake\Datasource\InvalidPropertyInterface
    [ArrayAccess] => ArrayAccess
    [JsonSerializable] => JsonSerializable
    [Cake\Datasource\EntityInterface] => Cake\Datasource\EntityInterface
)
```

As a screenshot:

![image](https://user-images.githubusercontent.com/5518087/70060547-0a224900-15e3-11ea-9f7e-9dcefcf2313e.png)

Apparently, `User`entity does implement `\Cake\Datatsource\EntityInterface`.

Not sure if it's relevant, but my PHP version is `PHP 7.0.33`

Any clues?

**Comment by ADmad** [comment]
Yes it is related to PHP version. I'll just update the readme to remove return type hint.
