### ISSUE TITLE
is there a way to prefix SocialProfiles table or change to a different name?

### ISSUE THREAD

**Issue by Mambix** [ADmad/cakephp-social-auth#66]
I'm working on a site that will use same project for .com and .org domain.
But both domains have their own Github app that will be used to login.

I need to separate socialProfile users for both apps and I don't want to create a full copy of the site and database just to achieve that.

Is it possible to prefix the database table and just use two separate tables for this?

**Comment by ADmad** [comment]
Use the `profileModel` config of middleware to use your own model.
