### ISSUE TITLE
Insert "User" before "SocialProfiles"

### ISSUE THREAD

**Issue by alexsmonte** [ADmad/cakephp-social-auth#68]
Is there a possibility to return only data before being entered in "SocialProfiles"?

I think it would be much more important for me to enter "User" first and then "SocialProfiles".

**Comment by ADmad** [comment]
Changing this line 

https://github.com/ADmad/cakephp-social-auth/blob/5444673f1e200a7e5c5f72348a79785cf84ddf43/src/Middleware/SocialAuthMiddleware.php#L288

to `if ($profile->isDirty() && !$profile->isNew()) {`  should achieve what you need.

The `_getUser()` called later on again check if profile is dirty and save it, so not persisting the profile entity earlier on shouldn't cause a problem.

**Comment by dereuromark** [comment]
This is closed, right?

**Comment by dereuromark** [comment]
But is this also available/needed for the 3.x branch?

**Comment by alexsmonte** [comment]
I think it could be an option!
