### ISSUE TITLE
Instagram compatibility

### ISSUE THREAD

**Issue by jkohon** [ADmad/cakephp-social-auth#69]
Hi! is there any example of working code for instagram?
Since Instagram API deprecation on 2020 is this plug in still compatible whit this API:
https://developers.facebook.com/docs/instagram-basic-display-api

**Comment by ADmad** [comment]
Check the docs of https://github.com/SocialConnect/auth

**Comment by jkohon** [comment]
Looked up for documentation on SocialConnect. There is no example or reference of how to configure the plugin for instagram login api.
