### ISSUE TITLE
feat: Allow users to customize finder conditions when matching a profile to a user

### ISSUE THREAD

**Issue by josegonzalez** [ADmad/cakephp-social-auth#7]
Maybe via some specified callback or a cake event?

[Find in question](https://github.com/josegonzalez/cakephp-social-auth/blob/patch-3/src/Middleware/SocialAuthMiddleware.php#L162)

**Comment by ADmad** [comment]
I can apply the "where" conditions first and then call finder (which is customizable) which would allow one to override the conditions if required.

**Comment by josegonzalez** [comment]
That works.

**Comment by ADmad** [comment]
Done
