### ISSUE TITLE
Cake3: Migration from hybrid auth

### ISSUE THREAD

**Issue by dereuromark** [ADmad/cakephp-social-auth#70]
Did anyone try to migrate from CakePHP 3 hybrid auth and existing
social_profiles table there (with lots of input/data) to this plugin?

If so, is there some docs on how to best do this with minimal effort?
In this case I think we need a different Migrations (diff) file etc.

**Comment by dereuromark** [comment]
I see a few issues that cannot easily be resolved probably.

before

            ->addColumn('email_verified', 'boolean', [
                'default' => false,
                'null' => false,
            ])
            ->addColumn('birth_date', 'string', [
                'default' => null,
                'limit' => 255,
                'null' => true,
            ])

after

            ->addColumn('email_verified', 'string', [
                'default' => null,
                'limit' => 255,
                'null' => true
            ])
            ->addColumn('birth_day', 'string', [
                'default' => null,
                'limit' => 255,
                'null' => true
            ])
            ->addColumn('birth_month', 'string', [
                'default' => null,
                'limit' => 255,
                'null' => true
            ])
            ->addColumn('birth_year', 'string', [
                'default' => null,
                'limit' => 255,
                'null' => true
            ])

and
- `username` / `full_name` => `display_name` ?
- `picture_url` => `photo_url`

Something like this should work:

```php
class CreateSocialProfiles extends AbstractMigration
{
    /**
     * @return void
     */
    public function change()
    {
        $table = $this->table('social_profiles');

        if ($table->exists()) {
            $this->migrateFromHybridAuth($table);
        } else  {
            $this->initalize($table);
        }
    }


    /**
     * @param \Phinx\Db\Table $table
     *
     * @return void
     */
    protected function migrateFromHybridAuth($table)
    {
        $table
            ->addColumn('access_token', 'blob')
            ->addColumn('username', 'string', [
                'default' => null,
                'limit' => 255,
                'null' => true,
            ])
            ->addColumn('full_name', 'string', [
                'default' => null,
                'limit' => 255,
                'null' => true,
            ])
            ->addColumn('birth_date', 'string', [
                'default' => null,
                'limit' => 255,
                'null' => true,
            ])
            ->addColumn('picture_url', 'string', [
                'default' => null,
                'limit' => 255,
                'null' => true,
            ])
            ->changeColumn('email_verified', 'boolean', [
                'default' => false,
                'null' => false,
            ])
            ->update();
    }

    /**
     * @param \Phinx\Db\Table $table
     *
     * @return void
     */
    protected function initialize($table)
    {
        $table = $this->table('social_profiles');
        $table
            ->addColumn('user_id', 'integer', [
                'default' => null,
                'limit' => 11,
                'null' => true,
            ])
            ->addColumn('provider', 'string', [
                'default' => null,
                'limit' => 255,
                'null' => false,
            ])
            ->addColumn('access_token', 'blob')
            ->addColumn('identifier', 'string', [
                'default' => null,
                'limit' => 255,
                'null' => false,
            ])
            ->addColumn('username', 'string', [
                'default' => null,
                'limit' => 255,
                'null' => true,
            ])
            ->addColumn('first_name', 'string', [
                'default' => null,
                'limit' => 255,
                'null' => true,
            ])
            ->addColumn('last_name', 'string', [
                'default' => null,
                'limit' => 255,
                'null' => true,
            ])
            ->addColumn('full_name', 'string', [
                'default' => null,
                'limit' => 255,
                'null' => true,
            ])
            ->addColumn('email', 'string', [
                'default' => null,
                'limit' => 255,
                'null' => true,
            ])
            ->addColumn('birth_date', 'string', [
                'default' => null,
                'limit' => 255,
                'null' => true,
            ])
            ->addColumn('gender', 'string', [
                'default' => null,
                'limit' => 255,
                'null' => true,
            ])
            ->addColumn('picture_url', 'string', [
                'default' => null,
                'limit' => 255,
                'null' => true,
            ])
            ->addColumn('email_verified', 'boolean', [
                'default' => false,
                'null' => false,
            ])
            ->addColumn('created', 'datetime', [
                'default' => null,
                'null' => true,
            ])
            ->addColumn('modified', 'datetime', [
                'default' => null,
                'null' => true,
            ])
            ->addIndex(
                [
                    'user_id',
                ]
            )
            ->create();
    }
}
```

**Comment by dereuromark** [comment]
The old one had two different callbacks afaik

        EventManager::instance()->on('HybridAuth.newUser', [$this, 'createUser']);
        EventManager::instance()->on('HybridAuth.login', [$this, 'updateUser']);

Is there anything similar that can be done here?
So we can use custom logic per type?

Now it is just 

        EventManager::instance()->on('SocialAuth.afterIdentify', [$this, 'updateUser']);

afaik.

**Comment by dereuromark** [comment]
The largest problem I have when migrating:
Session contains the user now as object instead of array which breaks everything.
```
Auth" => array:1 [▼
    "User" => App\Model\Entity\User
```
It should be an array though (by default)

**Comment by dereuromark** [comment]
Permissions seem to also have some issues
Cant seem to get the email anymore.

    "email" => null
    "email_verified" => false

now, even though I transformed `'scope' => 'user:email,repo',` into `'scope' => ['user:email', 'repo'],``array structure.

**Comment by dereuromark** [comment]
OK, I have to abort for now.
https://github.com/SocialConnect/auth/blob/1.x/src/OAuth2/Provider/GitLab.php#L78-L85
This is what we need to use inside cake3 due to the constraints ( https://github.com/ADmad/cakephp-social-auth/blob/master/composer.json#L7 ) - and that is deprecated way and triggers an email every time called/used.

**Comment by dereuromark** [comment]
in 4.x the migration from hybrid to social so far worked quite nicely

one remaining issue is the remaining event as I mentioned before

    // AppController initialize
    EventManager::instance()->on('SocialAuth.afterIdentify', [$this->UserComponent, 'afterIdentify']);

inside the controller is now not invoked anymore, as the middleware doesn't reach it on that part.
How would you handle setting the flash message to the user?
We need Session access, so somewhere in the controller scope would probably be good.

We should then document this part about being able to give the visual feedback for successful login.

**Comment by ADmad** [comment]
I can add a query string to the redirection URL to indicate success. So depending on the query string you can either set flash message (which would be consumed in the same request) or you can directly check for the query string in template and show a notification.

Currently when auth through social provider fails then too a query string `?error=<msg>` is used.

**Comment by dereuromark** [comment]
I see. I guess that sounds consistent then.

**Comment by dereuromark** [comment]
Oh wait
The ?error would only be relevant for the login action, thus AccountController
Here we can do that quite isolated

With the success message and a redirect anywhere in the system, this would need to be global in AppController
I wonder if that could also conflict with other query strings and stuff. E.g. filtering

Maybe we should find a different (callback or hook based) system here.

**Comment by dereuromark** [comment]
I think this is resolved in https://github.com/ADmad/cakephp-social-auth/pull/89
Also added some docs for flash messages.
