### ISSUE TITLE
Compatibility with cakephp/authentication

### ISSUE THREAD

**Issue by HJerem** [ADmad/cakephp-social-auth#73]
Hi, I've migrated from `AuthComponent` to `cakephp/authentication` as mentioned in the official CakePHP documentation.
But cakephp-social-auth doesn't seem to work anymore with `cakephp/authentication`.
How to make it work?
I didn't find any information about social auth in the `cakephp/authentication` documentation.
So I don't know how I can implement something like that.

**Comment by ADmad** [comment]
Use the `sessionKey` config of the `SocialAuthMiddleware` to same name as used by the `cakephp/authentication` to store user record in session.
