### ISSUE TITLE
Issue with github provider

### ISSUE THREAD

**Issue by ADmad** [ADmad/cakephp-social-auth#80]
From Cake's Slack

> It has drawbacks for us and github provider. It doesnt work the way it is documented it seems as the email is not possible to be returned anymore. It works well, if you only need username for identification etc. So i might have to consider using the hybrid auth in cake4 again.
19:48
I tried the hidden feature

> 'fetch_emails' => true,

> but that also doesnt seem to work anymore (silent failure)

**Comment by ADmad** [comment]
@dereuromark The fetching of email when `fetch_emails` option is `true` seems to he handled here:
https://github.com/SocialConnect/auth/blob/master/src/OAuth2/Provider/GitHub.php#L101-L107

If you can debug and provide some info or fix I can get it sorted out (and get `fetch_emails` option documented).

**Comment by dereuromark** [comment]
So far, I only get "API response with error code"
when it tries to execute

    $this->request('GET', 'user/emails', [], $accessToken);

**Comment by ADmad** [comment]
Have you included `user:email` scope in the provider config https://developer.github.com/apps/building-oauth-apps/understanding-scopes-for-oauth-apps/#normalized-scopes ?

On this demo https://sc.lowl.io/ github's permission page shows "Private email addresses" in the perms list. Do you get the same?

**Comment by dereuromark** [comment]
I used
```php
                            'scope' => [
                                'email',
                            ],
                            'options' => [
                                'identity.fields' => [
                                    'email',
                                ],
                                'fetch_emails' => true,
                            ],
```

**Comment by ADmad** [comment]
Try with `'scope' => ['user:email']`.

**Comment by dereuromark** [comment]
I was fooled by the hybrid auth config I guess.
With the right scope prefix it works indeed. Sry for that.

**Comment by ADmad** [comment]
No problem.
