### ISSUE TITLE
CakePHP4 - Social Auth Integration.

### ISSUE THREAD

**Issue by marchael21** [ADmad/cakephp-social-auth#81]
I'm new to CakePHP. Just want to ask if it's possible to use this plugin on the CakePHP4?

**Comment by ADmad** [comment]
You can use the `cake-4.x` branch.

**Comment by BassemN** [comment]
@marchael21 You can install the plugin for CakePHP4 by using the following command
`composer require admad/cakephp-social-auth:dev-cake-4.x`

**Comment by marchael21** [comment]
Thank you @ADmad and @BassemN. Cheers!
