### ISSUE TITLE
Workflows

### ISSUE THREAD

**Issue by dereuromark** [ADmad/cakephp-social-auth#85]
Before we go into tagging more stable, I wanted to discuss a few scenarios that might either just need documentation - or we need to think about how those could achieved with current way.

### Pending email
If an email right now is not "confirmed", the user status shouldn't be active for some apps that require a confirmed email when logging in through GitHub, ...
How could we make this user pending in the app until that one step is complete and registration is officially done, making him a full member with all access?

### Registration completion
Some apps require a few more "mandatory" fields after this Social login.
E.g. birthday, gender, ...
Especially if the provider doesn't provide them, there should be a "tmp" auth access then until the registration is complete and you can now access all actions.
With current way you would already be logged in as full member.
Are there any ideas how this could be done, or is this out of scope?

**Comment by ADmad** [comment]
> Pending email

When using a social provider isn't it assumed that the email got from the provider has been confirmed by them?

> Registration completion

This can be managed with user status isn't it? They default status for a new user could be "incomplete". So your app would check the status and redirect user accordingly to the profile completing page.

**Comment by dereuromark** [comment]
> When using a social provider isn't it assumed that the email got from the provider has been confirmed by them?

GitHub provides "email_confirmed" 0/1
So I guess this is not always the case
But sure, this can probably be just something the implementing app has to think about then.

**Comment by dereuromark** [comment]
Do you think you can do a beta at this point?
