### ISSUE TITLE
Access token usage

### ISSUE THREAD

**Issue by dereuromark** [ADmad/cakephp-social-auth#94]
in hybrid auth the following was used to not use a global (bot) config, but the own users permissions to access github (and thus their own rate limit):
```php
        $store = $this->request->getSession()->read('HA::STORE');
        Configure::write('Release.webBot', true);
        if ($store && !empty($store['hauth_session.github.token.access_token'])) {
            preg_match('/"(.+)"/', $store['hauth_session.github.token.access_token'], $matches);
            if ($matches) {
                $token = $matches[1];
                Configure::write('Release.token', $token);
                Configure::write('Release.webBot', false);
            }
        }
```

With social auth I don't think there is such a store anymore
So I tried
```php
        /** @var \SocialConnect\OAuth2\AccessToken|null $token */
        $token = $this->request->getSession()->read('Auth.User.social_profile.access_token');
        Configure::write('Release.webBot', true);
        if ($token && $token->getToken()) {
            Configure::write('Release.token', $token->getToken());
            Configure::write('Release.webBot', false);
        }
```

But that does not work.

**Comment by ADmad** [comment]
For the default config the user record would be under `Auth` key, so the session path you need to check is `Auth.social_profile.access_token`.

I see the the readme and docblock incorrectly mentions the default key as `Auth.User`. I must have missed updating docs when the code was updated to match the default key used by authentication plugin.

**Comment by dereuromark** [comment]
Well, the thing is that it is there, the token exists under also the user nesting.
Otherwise it wouldn't go into the condition to set it to the config, and the webpage then breaking with a not found issue.

I also checked the content, and it contains a real ascii char, e.g. `ce129dc60b2531690efb203cb7ea507f4666fc91`

But it just doesn't work anymore as the old hybrithauth one did.
Is it possible that there is a scenario where the session exceeds the token lifetime?
Even though this is happening already very early now. So quite unlikely as well.

**Comment by dereuromark** [comment]
The key that you mentions is not filled.
But there is a `'oauth2_state' => '9e4bf34de22890f79cc325275ea1cbax'`
directly on root level.

**Comment by dereuromark** [comment]
Is it possible that a login with a 2nd device would invalidate the first token in session in the other device/browser?
That would explain it.
This behavior wasn't part of HybridAuth afaik

It now seems to have a different token in social_profiles table in DB for the 2nd browser than is in session still.

**Comment by ADmad** [comment]
I am not exactly sure how Github (or other Oauth2 providers) deal with the tokens. These are most likely short lived tokens so not sure for how long they are valid or whether logging in through another devices invalidates a previous token.

**Comment by ADmad** [comment]
What error do you get when trying to use the token? That might provide some info. Here's the list of possible errors: https://docs.github.com/en/free-pro-team@latest/developers/apps/authorizing-oauth-apps#error-codes-for-the-device-flow

**Comment by dereuromark** [comment]
I added a `?token=own` to toggle the usage of own vs bot token usage (to avoid rate limit we want to have each dev use their own through their account if possible).

And it seems that the token doesn't work for private repos anymore.
Now trying to fetch those it fails.
So my guess is that permissions changed on what one can do with this token given.
```
'scope' => [
            'user:email',
        ],
        'options' => [
            'identity.fields' => [
                'email',
            ],
            'fetch_emails' => true,
        ],
```
Is pretty much the same as it was before afaik.

**Comment by ADmad** [comment]
Yes it could an issue with scope. Since the token was generated only for `user:email` scope, it might not allow accessing other API endpoints. So you'll have to included additional scopes you need.

**Comment by dereuromark** [comment]
Whats the key difference here from hybrid to social?
That it now seems to run into this issue for non bot accounts?

On the page for apps I read:

> API access to private organization resources is not available for unapproved OAuth Apps. In addition, there are no privileged create, update, or delete actions on public organization resources.

Maybe that now also plays into this.
But I didn't change anything on the github side or oauth app side, so this must still be completely something from social auth side.
